### ISSUE TITLE
Tipping amount limited to 3 a day.

### ISSUE THREAD

**Issue by splawik21** [gass-git/tip-me-dash#2]
This is some kind of a hard restriction don't you think?
<img width="277" alt="image" src="https://user-images.githubusercontent.com/14001049/125459444-fda9d137-08d1-413a-a90e-ec0f4a4eca69.png">

**Comment by gass-git** [comment]
Yes it is, I'm going to limit it at 5 for now. It's mainly to prevent spam. I have a max of API requests/hour.  What do you think? Maybe restrict per hour instead of per day?

**Comment by splawik21** [comment]
I think you need to see further api calls and check if your limits are going to be fulfilled. 5 tips a day sounds good to me.
